# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# Spring Application
# ===============================
spring.application.name=backend

# ===============================
# MySQL Database Connection
# ===============================

# local 용
# spring.datasource.url=jdbc:mysql://localhost:3306/designer?allowPublicKeyRetrieval=true

# 배포용
spring.datasource.url: jdbc:mysql://designer-mysql:3306/designer?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always

# ===============================
# MyBatis Settings
# ===============================

# mapper.xml íì¼ ìì¹ (resources/mapper í´ë ìë)
mybatis.mapper-locations=classpath:mapper/*.xml

# DTO/VO í´ëì¤ í¨í¤ì§ ì§ì  (alias ìë ë±ë¡)
mybatis.type-aliases-package=com.designer.auth.dto

# DBì snake_case ì»¬ë¼ì Javaì camelCaseë¡ ìë ë§¤í
mybatis.configuration.map-underscore-to-camel-case=true

# ===============================
# AWS S3 Settings
# ===============================

# S3 ë²í· ì´ë¦
aws.s3.bucket-name=treatment-image

# S3 ë¦¬ì 
aws.s3.region=ap-northeast-2

# ìë¡ëì© Presigned URL ë§ë£ ìê° (ì´)
aws.s3.presign.upload-expiration-seconds=300

# ë¤ì´ë¡ëì© Presigned URL ë§ë£ ìê° (ì´)
aws.s3.presign.download-expiration-seconds=300

# ===============================
# Logging
# ===============================

# Mapper í¨í¤ì§ SQL ë¡ê·¸ ì¶ë ¥
logging.level.com.designer.auth.mapper=DEBUG
